---

- name: Append libvirt group with user "{{ lookup('env', 'USER') }}"
  ansible.builtin.user:
    name: "{{ lookup('env','USER') }}"
    groups: libvirt
    append: true

- name: Install libvirt-python
  ansible.builtin.pip:
    name: libvirt-python

- name: Install list of package
  ansible.builtin.apt:
    name: '{{ libvirt_labs_init_needed_packages }}'
    state: present
  when: ansible_facts['os_family'] == 'Debian'

...
